### ISSUE TITLE
Joint calling and hg38

### ISSUE THREAD

**Issue by llllaaaa** [aquaskyline/16GT#1]
Hi @aquaskyline 

I have two questions about 16GT. First, does it support trio joint calling? Can I use all the samples as the input of bam2snapshot? Second, is it compatible with the hs38dh reference genome? Is there something like the BadMateFilter in GATK that will cause problems when calling variants on the ALT contigs?

Thanks

**Comment by aquaskyline** [comment]
16GT doesn't do population calling, you can only provide a BAM a time. 16GT is compatible with hs38dh as long as the input BAM file was generated using the same reference genome. 16GT doesn't treat ALT contigs specifically, variants on ALT contigs will be generated if alignments exist. If you want to eliminate the results on ALT contigs, filter the VCF file afterward or align to a reference without the ALT contigs.
