### ISSUE TITLE
make error 16GT on mac

### ISSUE THREAD

**Issue by Espinosa-Gongora** [aquaskyline/16GT#10]
Hello,
I'm on mac os 10.15.4 (Catalina) trying to install 16GT.
My clang version: Apple clang version 11.0.3 (clang-1103.0.32.59)
I have latest gcc (g++-9)
My try:
$ git clone https://github.com/aquaskyline/16GT
$ cd 16GT
$ make
g++ -O3 -funroll-loops -fomit-frame-pointer -maccumulate-outgoing-args -funroll-loops -static-libgcc -mpopcnt -fopenmp -fpermissive -w -c snapshotSnpcaller.cpp -o snapshotSnpcaller.o
clang: error: unknown argument: '-maccumulate-outgoing-args'
clang: error: unsupported option '-fopenmp'
make: *** [snapshotSnpcaller.o] Error 1

Thank you in advance :-)

**Comment by aquaskyline** [comment]
we are sorry that 16GT can only be compiled in Linux.

**Comment by Espinosa-Gongora** [comment]
I see :-) 
Thank you
