### ISSUE TITLE
How to call somatic mutations using 16GT?

### ISSUE THREAD

**Issue by Jemimacat** [aquaskyline/16GT#4]
Hi. I've downloaded and installed 16GT and plan to call somatic mutations. However, I can not find the proper command to call. Would somebody could tell me about that? Thank you.

**Comment by slw287r** [comment]
According to their paper:
> In the current implementation, 16GT can only be applied to germline variant detection. In the future, we will enhance 16GT to support multi-sample variant calling and GVCF output and to support somatic variant detection and extend the model to support variant calling in species with more than 2 haplotypes.

somatic detection is going to be supported while the detailed timeline is not mentioned.

Richard

**Comment by aquaskyline** [comment]
16GT doesn't support somatic mutation calling yet.
