### ISSUE TITLE
How to set CPU number? Number of threads? Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by scotty323** [aquaskyline/16GT#8]
~/16GT> /home/tao/16GT/bam2snapshot -i /home/tao/seq/jelly_out_chr_pilon.fasta.rename.fa.index -b /home/newdisk/tao/z_final_new/432.sort.bam -b /home/newdisk/tao/z_final_new/ZGWS.sort.bam -b /home/newdisk/tao/z_final_new/543.sort.bam -b /home/newdisk/tao/z_final_new/ZO1.sort.bam -b /home/newdisk/tao/z_final_new/AL1.sort.bam -b /home/newdisk/tao/z_final_new/PZ.sort.bam -b /home/newdisk/tao/z_final_new/BG.sort.bam -b /home/newdisk/tao/z_final_new/PZHBL.sort.bam -b /home/newdisk/tao/z_final_new/BYDHL.sort.bam -b /home/newdisk/tao/z_final_new/QBL.sort.bam -b /home/newdisk/tao/z_final_new/DH2.sort.bam -b /home/newdisk/tao/z_final_new/SRR2131192.sort.bam -b /home/newdisk/tao/z_final_new/FH.sort.bam -b /home/newdisk/tao/z_final_new/T1-6.sort.bam -b /home/newdisk/tao/z_final_new/HLJHL.sort.bam -b /home/newdisk/tao/z_final_new/WSHL.sort.bam -b /home/newdisk/tao/z_final_new/JX.sort.bam -b /home/newdisk/tao/z_final_new/XHHL.sort.bam -b /home/newdisk/tao/z_final_new/XL.sort.bam -o /home/newdisk/tao/z_final_new/16GTotherlotus
Loading reference...
Done.
464 chromosomes, 821160161bp in length.
Parameters:
    #CPUThreads=16
    TrimSize=5
    SoftClipThreshold=5
    MQThreshold=0
    indelWeightThreshold=1
Allocating memory...
Done.
Time elapsed by now is 0 seconds.
Updating snapshot...
Processing /home/newdisk/tao/z_final_new/432.sort.bam...
Segmentation fault (core dumped)

~~~
Dear friend, you tool does not have any parameters for changing the number of threads.

Please let us know how to set it!

**Comment by animesh** [comment]
seems like changing the "CPUThreads" in "bam2snapshot.ini " https://github.com/aquaskyline/16GT/blob/master/bam2snapshot.ini might achieve this objective
